### ISSUE TITLE
AriaTSset_up

### ISSUE THREAD

**Issue by Nourmain** [aria-tools/ARIA-tools#387] opened 2023-11-28 01:43 UTC
I am using AriaTS_setup notebook to prepare stack of interferograms to use it in the "smallbaselineApp_aria" . when I hit the command :

!ariaTSsetup.py -f 'products/*.nc' -b '36.97 39.04 35.73 38.99' -d Download --mask Download

I got this error:

Shapefile ./user_bbox.json created for input user bounds.
Multi-core version
All (45) GUNW products meet spatial bbox criteria.
Group GUNW products into spatiotemporally continuous interferograms.
All (15) interferograms are spatially continuous.
Thread count specified for gdal multiprocessing = 2
/home/jovyan/.local/ARIA-tools/tools/ARIAtools/shapefile_util.py:70: ShapelyDeprecationWarning: The 'type' attribute is deprecated, and will be removed in the future. You can use the 'geom_type' attribute instead.
if file_bbox.type == 'Polygon': file_bbox = [file_bbox]
/home/jovyan/.local/ARIA-tools/tools/ARIAtools/shapefile_util.py:70: ShapelyDeprecationWarning: The 'type' attribute is deprecated, and will be removed in the future. You can use the 'geom_type' attribute instead.
if file_bbox.type == 'Polygon': file_bbox = [file_bbox]
/home/jovyan/.local/ARIA-tools/tools/ARIAtools/shapefile_util.py:70: ShapelyDeprecationWarning: The 'type' attribute is deprecated, and will be removed in the future. You can use the 'geom_type' attribute instead.
if file_bbox.type == 'Polygon': file_bbox = [file_bbox]
/home/jovyan/.local/ARIA-tools/tools/ARIAtools/shapefile_util.py:70: ShapelyDeprecationWarning: The 'type' attribute is deprecated, and will be removed in the future. You can use the 'geom_type' attribute instead.
if file_bbox.type == 'Polygon': file_bbox = [file_bbox]
/home/jovyan/.local/ARIA-tools/tools/ARIAtools/shapefile_util.py:70: ShapelyDeprecationWarning: The 'type' attribute is deprecated, and will be removed in the future. You can use the 'geom_type' attribute instead.
if file_bbox.type == 'Polygon': file_bbox = [file_bbox]
/home/jovyan/.local/ARIA-tools/tools/ARIAtools/shapefile_util.py:70: ShapelyDeprecationWarning: The 'type' attribute is deprecated, and will be removed in the future. You can use the 'geom_type' attribute instead.
if file_bbox.type == 'Polygon': file_bbox = [file_bbox]
/home/jovyan/.local/ARIA-tools/tools/ARIAtools/shapefile_util.py:70: ShapelyDeprecationWarning: The 'type' attribute is deprecated, and will be removed in the future. You can use the 'geom_type' attribute instead.
if file_bbox.type == 'Polygon': file_bbox = [file_bbox]
/home/jovyan/.local/ARIA-tools/tools/ARIAtools/shapefile_util.py:70: ShapelyDeprecationWarning: The 'type' attribute is deprecated, and will be removed in the future. You can use the 'geom_type' attribute instead.
if file_bbox.type == 'Polygon': file_bbox = [file_bbox]
/home/jovyan/.local/ARIA-tools/tools/ARIAtools/shapefile_util.py:70: ShapelyDeprecationWarning: The 'type' attribute is deprecated, and will be removed in the future. You can use the 'geom_type' attribute instead.
if file_bbox.type == 'Polygon': file_bbox = [file_bbox]
/home/jovyan/.local/ARIA-tools/tools/ARIAtools/shapefile_util.py:70: ShapelyDeprecationWarning: The 'type' attribute is deprecated, and will be removed in the future. You can use the 'geom_type' attribute instead.
if file_bbox.type == 'Polygon': file_bbox = [file_bbox]
/home/jovyan/.local/ARIA-tools/tools/ARIAtools/shapefile_util.py:70: ShapelyDeprecationWarning: The 'type' attribute is deprecated, and will be removed in the future. You can use the 'geom_type' attribute instead.
if file_bbox.type == 'Polygon': file_bbox = [file_bbox]
/home/jovyan/.local/ARIA-tools/tools/ARIAtools/shapefile_util.py:70: ShapelyDeprecationWarning: The 'type' attribute is deprecated, and will be removed in the future. You can use the 'geom_type' attribute instead.
if file_bbox.type == 'Polygon': file_bbox = [file_bbox]
/home/jovyan/.local/ARIA-tools/tools/ARIAtools/shapefile_util.py:70: ShapelyDeprecationWarning: The 'type' attribute is deprecated, and will be removed in the future. You can use the 'geom_type' attribute instead.
if file_bbox.type == 'Polygon': file_bbox = [file_bbox]
/home/jovyan/.local/ARIA-tools/tools/ARIAtools/shapefile_util.py:70: ShapelyDeprecationWarning: The 'type' attribute is deprecated, and will be removed in the future. You can use the 'geom_type' attribute instead.
if file_bbox.type == 'Polygon': file_bbox = [file_bbox]
/home/jovyan/.local/ARIA-tools/tools/ARIAtools/shapefile_util.py:70: ShapelyDeprecationWarning: The 'type' attribute is deprecated, and will be removed in the future. You can use the 'geom_type' attribute instead.
if file_bbox.type == 'Polygon': file_bbox = [file_bbox]
/home/jovyan/.local/ARIA-tools/tools/ARIAtools/shapefile_util.py:70: ShapelyDeprecationWarning: The 'type' attribute is deprecated, and will be removed in the future. You can use the 'geom_type' attribute instead.
if file_bbox.type == 'Polygon': file_bbox = [file_bbox]
Download/cropping DEM
/home/jovyan/.local/ARIA-tools/tools/ARIAtools/shapefile_util.py:70: ShapelyDeprecationWarning: The 'type' attribute is deprecated, and will be removed in the future. You can use the 'geom_type' attribute instead.
if file_bbox.type == 'Polygon': file_bbox = [file_bbox]
Traceback (most recent call last):
File "/home/jovyan/.local/ARIA-tools/tools/bin/ariaTSsetup.py", line 18, in
main(inps)
File "/home/jovyan/.local/ARIA-tools/tools/ARIAtools/tsSetup.py", line 432, in main
inps.demfile, demfile, Latitude, Longitude = prep_dem(
^^^^^^^^^
File "/home/jovyan/.local/ARIA-tools/tools/ARIAtools/extractProduct.py", line 355, in prep_dem
gdal.Warp(aria_dem, demfilename, format=outputFormat,
File "/home/jovyan/.local/envs/earthscope_insar/lib/python3.11/site-packages/osgeo/gdal.py", line 776, in Warp
srcDSTab = [Open(srcDSOrSrcDSTab)]
^^^^^^^^^^^^^^^^^^^^^
File "/home/jovyan/.local/envs/earthscope_insar/lib/python3.11/site-packages/osgeo/gdal.py", line 4716, in Open
return _gdal.Open(*args)
^^^^^^^^^^^^^^^^^
RuntimeError: `./DEM/SRTM_3arcsec_uncropped.tif' not recognized as a supported file format.
the DEM folder has just one file SRTM_3arcsec_uncropped.tif.

I have my API key , and using Windows11.

Thanks.

**Comment by bbuzzanga** [comment] 2023-11-28 16:45
Duplicate of #385

**Closed as completed by bbuzzanga** 2023-11-28 16:45 UTC
Labels: bug
