### ISSUE TITLE
Downsampling large data sets

### ISSUE THREAD

**Issue by rzinke** [aria-tools/ARIA-tools#118] opened 2019-09-19 22:28 UTC
Hello,
I am trying to use a large number of ARIA products (several thousand frames over ~15 degrees of latitude) to construct a time series through MintPy. I am running into an issue that when I invert the network of interferograms, processing fails with a Memory Error. The ideal solution would be to downsample the extracted ARIA products to a lower spatial resolution before entering the MintPy workflow. I suppose this could be carried out in the TSsetup step (?).

Would it be possible to introduce an option for setting the spatial resolution of your ARIA data set for time series analysis?  E.g., with options such as -xres and -yres of the pixel sizes?

Thank you

**Comment by dbekaert** [comment] 2019-09-19 22:40
The TS program is a workflow which calls the ARIA tools in a modular fashion.
This means the downsampling option needs to be implemented at a lower level in the code (export product level). The downsampling should be expressed as a square resolution  in degree/seconds units such it is  GDAL compatibility. A danger will exist that users make the resolution finer than the source data which is something that should be avoided. Additional care will need to be provided to the handling of connected components.

**Comment by dbekaert** [comment] 2019-09-20 14:37
Tagging in @sssangha to give you a few more pointers.

**Comment by ehavazli** [comment] 2019-09-20 18:01
Hi @rzinke ,

If you can load the data to mintpy (prep_aria.py works without failing) you can multi look the data before running smallbaselineApp.py.
try using:
```
multilook.py inputs/ifgramStack.h5 -r 57 -a 21
```

**Comment by rzinke** [comment] 2019-09-20 18:10
Hi all,
Thanks for the thoughts and tips. 
In terms of mulitlooking in MintPy itself, I tried using the multilook.py function after prep_aria and before smallbaselineApp. Yunjun and I worked out how to adapt this to our georeferenced data, and it worked on a small test data set. But multilook.py itself crashed with a Memory Error when I applied it to our full data set. 

For now, I think the best (short-term) approach is to downsample our data in ARIA-tools. Yesterday, @sssangha and I worked out a way to specify the pixel resolution in TSsetup. I can forward you my scripts and we can write up our "lessons learned" for that. It's still a work in progress and I am testing it right now.

**Comment by dbekaert** [comment] 2019-09-20 19:15
@rzinke suggest to work on a branch and we can do testing on our end. Would be good to capture the proposed changes for review.

**Comment by rzinke** [comment] 2019-09-20 20:08
Yep, I will create a branch and push the results this afternoon. More then.

**Comment by rzinke** [comment] 2019-09-20 20:28
I do not think I have editing permission for aria-tools. I cannot push my new branch to the site, nor seem to create a new branch on the main github page.

**Comment by dbekaert** [comment] 2019-09-20 21:31
Let us know which branch you are developing on at your fork and we will pull to test. Final integration is done by issuing a PR from your branch to the dev. It gets merged after review and passing our tests.

**Comment by rzinke** [comment] 2019-09-20 22:02
Great. It's on the dev branch of my fork: https://github.com/rzinke/ARIA-tools
Pass the ariaTSsetup.py -r 0.0025 (9 arc seconds) or similar

**Comment by ehavazli** [comment] 2020-01-16 19:31
I am closing this issue since multi-looking is now implemented in ARIA-tools.

**Closed as completed by ehavazli** 2020-01-16 19:31 UTC

**Comment by KASHKASHOPTIMUS** [comment] 2022-08-16 20:49
![145](https://user-images.githubusercontent.com/107583734/184982259-faadcf06-7a5a-4c1b-b108-48cb0144aed4.JPG)
I am trying to use mintpy smallbaselineApp.py command for processing of metadata from GUNW .nc files. I am getting this error what could be the mistake?

**Comment by bbuzzanga** [comment] 2022-08-17 00:29
Open new issues for new issues. Unclear if this is a mintpy issue or ARIA-tools issue.  Provide steps to reproduce.
