### ISSUE TITLE
Unexpected marker ID when multilooking

### ISSUE THREAD

**Issue by rzinke** [aria-tools/ARIA-tools#129] opened 2020-01-16 18:34 UTC
Hello, I have been experimenting with the multilooking feature. For my data set, when I set the multilook parameter to 3 and specify a bounding box, the ariaTSsetup.py routine appears to work through all the given products. However, when I try to apply the next step, MintPy's prep_aria.py, I get an error saying one of the files cannot be read. When I try to look at the extracted unwrapped interferogram that is causing the problem using gdalinfo, I get the following error message: 

(ARIA-tools) [rzinke@sar unwrappedPhase]$ gdalinfo 20160903_20160717
ERROR 1: A marker ID was expected (0xff--) instead of 0000cf40

ERROR 1: opj_read_header() failed
gdalinfo failed - unable to open '20160903_20160717'.

This is odd, because all of the other standard products worked in this procedure -- that is, if I toss out that one product, a can run the process from product download to timeseries computation without issue. Furthermore, no errors result when I run the routine with the specified bounding box but without multilooking. Similarly, no errors result when I run the routine without specifying a bounding box but with multilooking. I have deleted and re-downloaded the products for that date, but the error persists. 

Has anyone encountered a similar issue in the past? Thanks for any assistance and happy to answer any questions.

**Comment by ehavazli** [comment] 2020-01-16 18:41
Hi @rzinke ,

Can you confirm the product is not corrupt, can you see the png of 20160903_20160717 in your unwrappedPhase folder?

**Comment by rzinke** [comment] 2020-01-16 18:49
Hi @ehavazli, the .png was generated and the image appears to be a valid, unwrapped interferogram.

**Comment by ehavazli** [comment] 2020-01-16 19:07
@rzinke, since you described it as a non-systematic error I am assuming it is an error related to the product. I would re-download that specific product and re-run ariaTSsetup.py again just to test. 

However, if it is not a key product for timeseries (e.g. keeping network connectivity), I would just discard it.

**Comment by rzinke** [comment] 2020-01-16 19:16
Agreed. 
I deleted and re-downloaded the products for that date, but the error still occurs.

I am continuing my data processing without that product, but I mostly wanted to put the word out there in case this issue is something more systematic. I'll send out the alert if I encounter it again.

**Comment by ehavazli** [comment] 2020-01-16 19:24
thanks for the feedback, I will look into it and try to reproduce the error.

**Comment by sssangha** [comment] 2020-01-16 19:29
@rzinke you had told me you also had this issue with a different pair (20160810_20160717). Just to clarify, are you having problem with both 20160810_20160717 and 20160903_20160717?

**Comment by sssangha** [comment] 2020-01-16 19:36
@rzinke, both were able to work on my end. Could you confirm which branch you have checked out? Make sure it is up to date with the latest dev commit. I.e. go to your ARIA-tools conda folder and enter: "git rev-parse --short HEAD"

**Comment by rzinke** [comment] 2020-01-16 19:38
Oh okay, I see the issue... When I run prep_aria the error message reports 20160810_... was the last file to be successful. 
The issue is with date pair 20160903_20160717
Apologies for the confusion

**Comment by rzinke** [comment] 2020-01-16 19:40
> @rzinke, both were able to work on my end. Could you confirm which branch you have checkout out? Make sure it is up to date with the latest dev commit. I.e. go to your ARIA-tools conda folder and enter: "git rev-parse --short HEAD"

OK. The command returns: 60a05a1

I am using the main fork, dev branch. Git remote show origin returns: https://github.com/aria-tools/ARIA-tools.git
git branch > dev

**Comment by sssangha** [comment] 2020-01-16 19:43
> >OK. The command returns: [60a05a1](https://github.com/aria-tools/ARIA-tools/commit/60a05a1327bd23f048677ef8fd87a5e607ca2952)
> 
> I am using the main fork, dev branch. Git remote show origin returns: https://github.com/aria-tools/ARIA-tools.git
> git branch > dev

Yeah looks like you checked out out the most recent version, but did you make sure to build/install it? Very strange, because I'm not getting that error nor do I recall ever seeing it.

**Comment by ehavazli** [comment] 2020-01-16 19:45
@rzinke this is what I get when I do gdalinfo on the extracted product

```
(aria) [~] havazli% gdalinfo 20160903_20160717
Driver: ENVI/ENVI .hdr Labelled
Files: 20160903_20160717
       20160903_20160717.aux.xml
       20160903_20160717.hdr
Size is 4212, 4025
Coordinate System is:
GEOGCRS["GCS_unknown",
    DATUM["D_unnamed",
        ELLIPSOID["Spheroid",6378137,298.257223563,
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["Degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["longitude",east,
            ORDER[1],
            ANGLEUNIT["Degree",0.0174532925199433]],
        AXIS["latitude",north,
            ORDER[2],
            ANGLEUNIT["Degree",0.0174532925199433]]]
Data axis to CRS axis mapping: 1,2
Origin = (87.889146828862295,38.583822407511697)
Pixel Size = (0.000833269014224,-0.000833432757003)
Metadata:
  Band_1=Band 1
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (  87.8891468,  38.5838224) ( 87d53'20.93"E, 38d35' 1.76"N)
Lower Left  (  87.8891468,  35.2292556) ( 87d53'20.93"E, 35d13'45.32"N)
Upper Right (  91.3988759,  38.5838224) ( 91d23'55.95"E, 38d35' 1.76"N)
Lower Right (  91.3988759,  35.2292556) ( 91d23'55.95"E, 35d13'45.32"N)
Center      (  89.6440114,  36.9065390) ( 89d38'38.44"E, 36d54'23.54"N)
Band 1 Block=4212x1 Type=Float32, ColorInterp=Undefined
  Min=-21.066 Max=29.543 
  Minimum=-21.066, Maximum=29.543, Mean=0.513, StdDev=7.050
  NoData Value=0
  Metadata:
    STATISTICS_APPROXIMATE=YES
    STATISTICS_MAXIMUM=29.543092727661
    STATISTICS_MEAN=0.51258259645877
    STATISTICS_MINIMUM=-21.066228866577
    STATISTICS_STDDEV=7.0498152415799
    STATISTICS_VALID_PERCENT=72.74
(aria) [MT-206092:~/Desktop/ROB/unwrappedPhase] havazli% gdalinfo 20160903_20160717
Driver: ENVI/ENVI .hdr Labelled
Files: 20160903_20160717
       20160903_20160717.aux.xml
       20160903_20160717.hdr
Size is 4212, 4025
Coordinate System is:
GEOGCRS["GCS_unknown",
    DATUM["D_unnamed",
        ELLIPSOID["Spheroid",6378137,298.257223563,
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["Degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["longitude",east,
            ORDER[1],
            ANGLEUNIT["Degree",0.0174532925199433]],
        AXIS["latitude",north,
            ORDER[2],
            ANGLEUNIT["Degree",0.0174532925199433]]]
Data axis to CRS axis mapping: 1,2
Origin = (87.889146828862295,38.583822407511697)
Pixel Size = (0.000833269014224,-0.000833432757003)
Metadata:
  Band_1=Band 1
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (  87.8891468,  38.5838224) ( 87d53'20.93"E, 38d35' 1.76"N)
Lower Left  (  87.8891468,  35.2292556) ( 87d53'20.93"E, 35d13'45.32"N)
Upper Right (  91.3988759,  38.5838224) ( 91d23'55.95"E, 38d35' 1.76"N)
Lower Right (  91.3988759,  35.2292556) ( 91d23'55.95"E, 35d13'45.32"N)
Center      (  89.6440114,  36.9065390) ( 89d38'38.44"E, 36d54'23.54"N)
Band 1 Block=4212x1 Type=Float32, ColorInterp=Undefined
  Min=-21.066 Max=29.543 
  Minimum=-21.066, Maximum=29.543, Mean=0.513, StdDev=7.050
  NoData Value=0
  Metadata:
    STATISTICS_APPROXIMATE=YES
    STATISTICS_MAXIMUM=29.543092727661
    STATISTICS_MEAN=0.51258259645877
    STATISTICS_MINIMUM=-21.066228866577
    STATISTICS_STDDEV=7.0498152415799
    STATISTICS_VALID_PERCENT=72.74
```

**Comment by rzinke** [comment] 2020-01-16 19:47
@sssangha, always good to check that it was reinstalled properly. To confirm, the date and time of items in my ARIA-tools bin folder match those of the download date, and I seem to remember reinstalling a few days ago. 

@ehavazli and @sssangha, I will try running a few more tests as you have done.

**Comment by rzinke** [comment] 2020-01-16 21:59
Hi all. I have done a bit more investigation. For starters, these two commands should allow for replication of the error within a minute or two: 
ariaDownload.py -t 41 -s 20160717 -e 20160903 -b '36.9 37.9 89.0 91.2'
ariaTSsetup.py -f 'products/*.nc' -w CroppedMultilooked -d download -b '36.9 37.9 89.0 91.2' -ml 3
and then $ gdalinfo CroppedMultilooked/unwrappedPhase/20160903_20160717 should show the error message: 
ERROR 1: A marker ID was expected (0xff--) instead of 0000cf40
ERROR 1: opj_read_header() failed

@ehavazli suggested that download the products directly from the ARIA Products page. Here are the links to those two products: 
https://aria-products.jpl.nasa.gov/search/dataset/grq_v2.0.1_s1-gunw-released/S1-GUNW-A-R-041-tops-20160903_20160717-115937-37105N_35229N-PP-b186-v2_0_1/S1-GUNW-A-R-041-tops-20160903_20160717-115937-37105N_35229N-PP-b186-v2_0_1.nc
https://aria-products.jpl.nasa.gov/search/dataset/grq_v2.0.1_s1-gunw-released/S1-GUNW-A-R-041-tops-20160903_20160717-120003-38595N_36721N-PP-939d-v2_0_1/S1-GUNW-A-R-041-tops-20160903_20160717-120003-38595N_36721N-PP-939d-v2_0_1.nc
I downloaded those two directly and received the same error when using the ariaTSsetup command above, including the --bbox and --multilook options

@sssangha suggested I check the product bounding boxes' shape files. When viewed in QGIS, the bounding boxes of the errant date (20160903_20160717) and the working dates match almost exactly. All overlie the "productBoundingBox.shp" file. 

Interestingly, when I change the --bbox option even slightly from '36.9 37.9 89.0 91.2' to '37 37.8 88.9 91.2', the error does not arise.

**Comment by ehavazli** [comment] 2020-01-16 22:23
@rzinke I followed your steps and produced the same error.

the fact that it doesn't arise when you change the bounding box makes me think that gdal error is due to the fact that the file is not properly extracted or written in the corners. it is probably because the standard products are not coregistered and may have (has in your case) slight difference at the edges.

I would recommend you going forward with the new bounding box.

**Comment by sssangha** [comment] 2020-01-16 22:53
@ehavazli @rzinke but then I don't understand why the other layers (e.g. amplitude, coherence) are downsampled just fine, but not the unw phase. Actually to be clear, all rasters are successfully downsampled, but the VRT just for the unw phase is corrupted.

I understand that this issue for this case is resolved by just adjusting the bbox, but I am concerned this may be an issue we will encounter again in the future.

**Comment by ehavazli** [comment] 2020-01-16 23:04
this is what I get with gdalinfo on unwrapped phase VRT:
```
(aria) [MT-206092:~/Desktop/ROB] havazli% gdalinfo CroppedMultilooked/unwrappedPhase/20160903_20160717.vrt
Driver: VRT/Virtual Raster
Files: CroppedMultilooked/unwrappedPhase/20160903_20160717.vrt
       CroppedMultilooked/unwrappedPhase/20160903_20160717
Size is 2640, 1200
Coordinate System is:
GEOGCRS["GCS_unknown",
    DATUM["D_unnamed",
        ELLIPSOID["Spheroid",6378137,298.257223563,
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["Degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["longitude",east,
            ORDER[1],
            ANGLEUNIT["Degree",0.0174532925199433]],
        AXIS["latitude",north,
            ORDER[2],
            ANGLEUNIT["Degree",0.0174532925199433]]]
Data axis to CRS axis mapping: 1,2
Origin = (89.000000000000000,37.899999999999999)
Pixel Size = (0.000833333333333,-0.000833333333333)
Metadata:
  Band_1=Band 1
Corner Coordinates:
Upper Left  (  89.0000000,  37.9000000) ( 89d 0' 0.00"E, 37d54' 0.00"N)
Lower Left  (  89.0000000,  36.9000000) ( 89d 0' 0.00"E, 36d54' 0.00"N)
Upper Right (  91.2000000,  37.9000000) ( 91d12' 0.00"E, 37d54' 0.00"N)
Lower Right (  91.2000000,  36.9000000) ( 91d12' 0.00"E, 36d54' 0.00"N)
Center      (  90.1000000,  37.4000000) ( 90d 6' 0.00"E, 37d24' 0.00"N)
Band 1 Block=128x128 Type=Float32, ColorInterp=Undefined
ERROR 1: A marker ID was expected (0xff--) instead of 0000cf40

ERROR 1: opj_read_header() failed
  NoData Value=0
```

and this is what I get for coherence VRT:

```
(aria) [MT-206092:~/Desktop/ROB] havazli% gdalinfo CroppedMultilooked/coherence/20160903_20160717.vrt
Driver: VRT/Virtual Raster
Files: CroppedMultilooked/coherence/20160903_20160717.vrt
       CroppedMultilooked/coherence/20160903_20160717_uncropped.vrt
Size is 880, 400
Coordinate System is:
GEOGCRS["unknown",
    DATUM["unnamed",
        ELLIPSOID["Spheroid",6378137,298.257223563,
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433,
            ID["EPSG",9122]]],
    CS[ellipsoidal,2],
        AXIS["latitude",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]],
        AXIS["longitude",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]]]
Data axis to CRS axis mapping: 2,1
Origin = (89.000000000000000,37.899999999999999)
Pixel Size = (0.002500000000000,-0.002500000000000)
Corner Coordinates:
Upper Left  (  89.0000000,  37.9000000) ( 37d54' 0.00"E, 89d 0' 0.00"N)
Lower Left  (  89.0000000,  36.9000000) ( 36d54' 0.00"E, 89d 0' 0.00"N)
Upper Right (  91.2000000,  37.9000000) ( 37d54' 0.00"E, 91d12' 0.00"N)
Lower Right (  91.2000000,  36.9000000) ( 36d54' 0.00"E, 91d12' 0.00"N)
Center      (  90.1000000,  37.4000000) ( 37d24' 0.00"E, 90d 6' 0.00"N)
Band 1 Block=512x128 Type=Float32, ColorInterp=Undefined
  NoData Value=0
```

The main difference is we don't extract the coherence as raster therefore the error message is not recorded in the VRT.

**Comment by dbekaert** [comment] 2020-01-16 23:06
Not sure as standard products are generated at a fixed grid using
pre-staged DEM. Spacing should be multiple but might have limitations at
machine precision rounding. Perhaps we should check impact of tap during
warping and downsampling. If we think gdal related could alsopost to gdal
mailing list. I jnderstand the full res file is fine and only issue of
downsampling?

**Comment by rzinke** [comment] 2020-01-16 23:12
@dbekaert "I jnderstand the full res file is fine and only issue of
downsampling?"
Yes... Downsampling and bounding box specification, it seems.

**Comment by sssangha** [comment] 2020-01-17 00:17
Ok, so @ehavazli and I realized that this issue resulted from the "average" resampling algorithm specified for the unwrapped phase. All the other full-res files were resampled with "lanczos", and setting this resampling algorithm for the unwrapped phase too eliminates this bug. This is something we should raise to the gdal community as David suggested. I will issue a PR shortly.

However, we still see a similar issue selectively for the ranked-resampling option, which essentially is also an average resampling algorithm in and of itself. I will raise a separate issue ticket concerning this as I continue to investigate the best solution.

**Comment by rzinke** [comment] 2020-01-17 00:22
Nice work, @sssangha and @ehavazli. Thanks for your persistence.

**Comment by dbekaert** [comment] 2020-02-25 15:56
@rzinke Based on the discussion you had on GDAL forum it is anticipated behavior for the averaging to have a a pixel shift. The lanczos appeared to remain sharper than the averaging. Based on the two items i understand that lanczos was the recommended re-sampling method. If confirmed and implemented, we can close this ticket.

**Closed as completed** 2020-04-25 22:04 UTC
